name: Linux.Do Auto Checkin

on:
  schedule:
    # 每天北京时间早上8点运行 (UTC 0点)
    - cron: '0 0 * * *'
  workflow_dispatch:  # 允许手动触发

jobs:
  checkin:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libnss3-dev \
          libatk-bridge2.0-dev \
          libdrm-dev \
          libxcomposite-dev \
          libxdamage-dev \
          libxrandr-dev \
          libgbm-dev \
          libxss-dev \
          libasound2-dev \
          libatspi2.0-dev \
          libgtk-3-dev
          
    - name: Install Chrome
      run: |
        wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Verify secrets
      run: |
        if [ -z "${{ secrets.LINUXDO_USERNAME }}" ]; then
          echo "Error: LINUXDO_USERNAME secret is not set"
          exit 1
        fi
        if [ -z "${{ secrets.LINUXDO_PASSWORD }}" ]; then
          echo "Error: LINUXDO_PASSWORD secret is not set"
          exit 1
        fi
        echo "Required secrets are configured"

    - name: Create .env file
      run: |
        echo "LINUXDO_USERNAME=${{ secrets.LINUXDO_USERNAME }}" >> .env
        echo "LINUXDO_PASSWORD=${{ secrets.LINUXDO_PASSWORD }}" >> .env
        if [ -n "${{ secrets.TELEGRAM_BOT_TOKEN }}" ]; then
          echo "TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}" >> .env
        fi
        if [ -n "${{ secrets.TELEGRAM_CHAT_ID }}" ]; then
          echo "TELEGRAM_CHAT_ID=${{ secrets.TELEGRAM_CHAT_ID }}" >> .env
        fi
        
    - name: Run checkin
      run: |
        echo "Starting Linux.Do checkin..."
        python main.py
      env:
        PYTHONUNBUFFERED: 1
        
    - name: Upload logs on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: debug-files
        path: |
          debug_*.png
          debug_*.html
        retention-days: 7
